version: '3.9'

services:
  db:
    ports:
      - "5432:5432"
    image: postgres
    restart: always
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./db_data/dvdrental.tar:/tmp/dvdrental.tar
    environment:
      POSTGRES_PASSWORD: mypass1234
